### ISSUE TITLE
Uncaught TypeError: editor.getElement is not a function

### ISSUE THREAD

**Issue by bashtian** [zmb3/gorename#16]
[Enter steps to reproduce below:]
1. Try to rename
2. Press escape

**Atom Version**: 1.6.2
**System**: Ubuntu 14.04.4
**Thrown From**: [gorename](https://github.com/zmb3/gorename) package, v1.0.1
### Stack Trace

Uncaught TypeError: editor.getElement is not a function

```
At /home/bashtian/.atom/packages/gorename/lib/gorename.js:48

TypeError: editor.getElement is not a function
    at RenameDialog.oncancel (/home/bashtian/.atom/packages/gorename/lib/gorename.js:48:16)
    at RenameDialog.cancel (/home/bashtian/.atom/packages/gorename/lib/rename-dialog.js:44:12)
    at HTMLDivElement.<anonymous> (/home/bashtian/.atom/packages/gorename/lib/rename-dialog.js:13:88)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:05.4.0 golang:gorename (atom-text-editor.editor.is-focused)
     -0:04.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
  2x -0:04.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:01.9.0 golang:gorename (atom-text-editor.editor.is-focused)
     -0:00.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:00.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
```

**Comment by zmb3** [comment]
Thanks for the report.  This is fixed in `v1.0.2`.
