### ISSUE TITLE
Failed to activate the gorename package

### ISSUE THREAD

**Issue by johanneswuerbach** [zmb3/gorename#17]
steps to reproduce below:
1. When starting atom

**Atom Version**: 1.7.0
**System**: Mac OS X 10.11.4
**Thrown From**: [gorename](https://github.com/zmb3/gorename) package, v1.0.2
### Stack Trace

Failed to activate the gorename package

```
At Cannot find module 'atom-package-deps'

Error: Cannot find module 'atom-package-deps'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.activate (/Users/johannes/.atom/packages/gorename/lib/main.js:17:5)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:754:28
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter-golint",
      "linter-golint",
      "linter-golint",
      "linter-golint",
      "linter-golint"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-handlebars, v1.3.0
auto-update-packages, v1.0.1
autocomplete-go, v1.0.6
autocomplete-paths, v1.0.2
builder-go, v1.0.0
editorconfig, v1.2.4
environment, v1.2.0
go-config, v1.1.4
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
language-terraform, v0.7.3
linter, v1.11.4
linter-eslint, v7.2.0
linter-js-yaml, v1.2.5
linter-jscs, v3.5.0
linter-jshint, v2.1.0
linter-jsonlint, v1.2.3
linter-rubocop, v0.4.7
linter-shellcheck, v1.1.0
minimap, v4.21.0
navigator-godef, v1.0.2
pretty-json, v1.0.3
tester-go, v1.0.4

# Dev
No dev packages
```

**Comment by zmb3** [comment]
hey @joefitzgerald any ideas on this one?

**Comment by joefitzgerald** [comment]
I think this may have been a network issue or some other issue resulting in npm dependencies not being pulled down. Please try uninstalling this package and then reinstalling it.
